# Generated by Django 5.1.3 on 2025-10-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodeid", models.CharField(max_length=100, unique=True)),
                (
                    "relay",
                    models.CharField(
                        choices=[("ON", "ON"), ("OFF", "OFF")],
                        default="ON",
                        max_length=3,
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="pzemreading",
            options={"ordering": ["-created"]},
        ),
        migrations.RenameField(
            model_name="pzemreading",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AddField(
            model_name="pzemreading",
            name="timestamp_ist",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="pzemreading",
            name="nodeid",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="pzemreading",
            name="relay",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
